<a href="https://colab.research.google.com/github/Kushal-Shr/Intro-to-AI/blob/main/ICP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row by 0

In [10]:
import numpy as np

In [11]:
arr = np.random.randint(1, 21, 15)
print(arr)

[11  7  3  5  6 18 14  1 16  8 18 19  3 11  8]


In [12]:
reshaped_arr = arr.reshape(3, 5)
print(reshaped_arr)

[[11  7  3  5  6]
 [18 14  1 16  8]
 [18 19  3 11  8]]


In [13]:
print(reshaped_arr.shape)

(3, 5)


In [14]:
for i in range(reshaped_arr.shape[0]):
    max_index = np.argmax(reshaped_arr[i])
    reshaped_arr[i][max_index] = 0

print(reshaped_arr)

[[ 0  7  3  5  6]
 [ 0 14  1 16  8]
 [18  0  3 11  8]]


b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [15]:
arr = np.zeros((4, 3), dtype=np.int32)
print(arr)

print(arr.shape)
print(type(arr))
print(arr.dtype)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
(4, 3)
<class 'numpy.ndarray'>
int32


c. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [17]:
A = np.array([[3, -2],
              [1,  0]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues: ", eigenvalues,)
print("Right eigenvectors:\n", eigenvectors)

Eigenvalues:  [2. 1.]
Right eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


d. Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [19]:
arr = np.array([[0, 1, 2],
                [3, 4, 5]])

diag_sum = np.trace(arr)
print(diag_sum)

4


e. Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]


In [20]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

reshaped = arr.reshape(2, 3)
print(arr)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
